### ISSUE TITLE
Add support for images in a directory structure

### ISSUE THREAD

**Issue by Gijsjan** [KBNLresearch/openjpeg-decoder-service#1]
This works: 
`http://localhost:9080/iiif-service/070.jp2/info.json`
but
`http://localhost:9080/iiif-service/facsimiles/070.jp2/info.json`
does not.

If an image is directly in the `/mount` dir it works fine, but when a directory structure is added the service returns a 404.

**Comment by renevanderark** [comment]
Hi Gijsjan,
Thanks for the feedback. Please retry with URLEncoded slashes for the path. It looks less pretty, but pretty forward slashes of unknown amount would be non-trivial to implement.

http://localhost:9080/iiif-service/facsimiles%2F070.jp2/info.json

Best,
René
