### ISSUE TITLE
rendundant steps in Dockerfile

### ISSUE THREAD

**Issue by atomotic** [KBNLresearch/openjpeg-decoder-service#2]
the app is located in `/service`, i think this two steps are redundant

https://github.com/KBNLresearch/openjpeg-decoder-service/blob/7f8af01b5ded24dc2803af18debdb649161f05c0/Dockerfile#L17-L18

**Comment by renevanderark** [comment]
I believe you're right. Seems like an artifact that needs cleaning up.
